version: '3.4'

services:
  echonotesbackend:
    image: ${DOCKER_REGISTRY-}echonotesbackend
    build:
      context: .
      dockerfile: EchoNotesBackend/Dockerfile
    ports:
      - "8083:8083"
      - "8082:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      db:
        condition: service_healthy

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Your_password123", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 5
